#!/usr/bin/env bash
# set -x

EXITCODE=0


debug=0;
build_type="prod"
clean=0
log_level="warn"

QBO_API_DB=~/.qbo/.api.db
QBO_CLI_DB=~/.qbo/.cli.db


name="qbo"
# docker manifest inspect eadem/api:latest

exit_on_error() {
    exit_code=$1
    last_command=${@:2}
    if [ $exit_code -ne 0 ]; then
        >&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
        exit $exit_code
    fi
}

possibleConfigs=(
	"/boot/config-$(uname -r)"
	"/usr/src/linux-$(uname -r)/.config"
	'/usr/src/linux/.config'
)

if [ $# -gt 0 ]; then
	CONFIG="$1"
else
	: "${CONFIG:="${possibleConfigs[0]}"}"
fi

if ! command -v zgrep &> /dev/null; then
	zgrep() {
		zcat "$2" | grep "$1"
	}
fi

kernelVersion="$(uname -r)"
kernelMajor="${kernelVersion%%.*}"
kernelMinor="${kernelVersion#$kernelMajor.}"
kernelMinor="${kernelMinor%%.*}"

is_set() {
	zgrep "CONFIG_$1=[y|m]" "$CONFIG" > /dev/null
}
is_set_in_kernel() {
	zgrep "CONFIG_$1=y" "$CONFIG" > /dev/null
}
is_set_as_module() {
	zgrep "CONFIG_$1=m" "$CONFIG" > /dev/null
}

color() {
	local codes=()
	if [ "$1" = 'bold' ]; then
		codes=("${codes[@]}" '1')
		shift
	fi
	if [ "$#" -gt 0 ]; then
		local code=
		case "$1" in
			# see https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
			black) code=30 ;;
			red) code=31 ;;
			green) code=32 ;;
			yellow) code=33 ;;
			blue) code=34 ;;
			magenta) code=35 ;;
			cyan) code=36 ;;
			white) code=37 ;;
		esac
		if [ "$code" ]; then
			codes=("${codes[@]}" "$code")
		fi
	fi
	local IFS=';'
	echo -en '\033['"${codes[*]}"'m'
}
wrap_color() {
	text="$1"
	shift
	color "$@"
	echo -n "$text"
	color reset
	echo
}

wrap_good() {
	echo "$(wrap_color "$1" white): $(wrap_color "$2" green)"
}
wrap_bad() {
	echo "$(wrap_color "$1" bold): $(wrap_color "$2" bold red)"
}
wrap_warning() {
    echo "$(wrap_color "$1" bold): $(wrap_color "$2" bold yellow)"
}

check_flag() {
	if is_set_in_kernel "$1"; then
		wrap_good "CONFIG_$1" 'enabled'
	elif is_set_as_module "$1"; then
		wrap_good "CONFIG_$1" 'enabled (as module)'
	else
		wrap_bad "CONFIG_$1" 'missing'
		EXITCODE=1
	fi
}

check_flags() {
	for flag in "$@"; do
		echo -n "- "
		check_flag "$flag"
	done
}

check_command() {
	if command -v "$1" > /dev/null 2>&1; then
		wrap_good "$1 command" 'available'
	else
		wrap_bad "$1 command" 'missing'
		EXITCODE=1
	fi
}

check_device() {
	if [ -c "$1" ]; then
		wrap_good "$1" 'present'
	else
		wrap_bad "$1" 'missing'
		EXITCODE=1
	fi
}

check_distro_userns() {
	source /etc/os-release 2> /dev/null || /bin/true
	if [[ "${ID}" =~ ^(centos|rhel)$ && "${VERSION_ID}" =~ ^7 ]]; then
		# this is a CentOS7 or RHEL7 system
		grep -q "user_namespace.enable=1" /proc/cmdline || {
			# no user namespace support enabled
			wrap_bad "  (RHEL7/CentOS7" "User namespaces disabled; add 'user_namespace.enable=1' to boot command line)"
			EXITCODE=1
		}
	fi
}

run_linux_tests() {
    if [ ! -e "$CONFIG" ]; then
        wrap_warning "warning: $CONFIG does not exist, searching other paths for kernel config ..."
        for tryConfig in "${possibleConfigs[@]}"; do
            if [ -e "$tryConfig" ]; then
                CONFIG="$tryConfig"
                break
            fi
        done
        if [ ! -e "$CONFIG" ]; then
            wrap_warning "error: cannot find kernel config"
            wrap_warning "  try running this script again, specifying the kernel config:"
            wrap_warning "    CONFIG=/path/to/kernel/.config $0 or $0 /path/to/kernel/.config"
        fi
    fi

    wrap_color "info: reading kernel config from $CONFIG ..." white
    echo


    check_cgroup() {

            cgroupSubsystemDir="$(awk '/[, ](cpu|cpuacct|cpuset|devices|freezer|memory)[, ]/ && $3 == "cgroup" { print $2 }' /proc/mounts | head -n1)"
            cgroupDir="$(dirname "$cgroupSubsystemDir")"
            cgroup_v=$(stat -fc %T /sys/fs/cgroup/)
            if [ -d "$cgroupDir/cpu" ] || [ -d "$cgroupDir/cpuacct" ] || [ -d "$cgroupDir/cpuset" ] || [ -d "$cgroupDir/devices" ] || [ -d "$cgroupDir/freezer" ] || [ -d "$cgroupDir/memory" ]; then
           
                    wrap_warn "cgroup hierarchy" "$cgroup_v"
            else
                    wrap_good "cgroup hierarchy" "$cgroup_v"

            fi
    }
    check_cgroup

    check_limit_under__max_user_watches() {
        if [ "$(cat "$1")" -lt "$2" ]; then
            wrap_warning "- $1" "$(cat "$1")"   
            echo "sudo sysctl fs.inotify.max_user_watches=2147483647"
            # read -n 1 -s -r -p "<Press any key to run command>"
            sudo sysctl fs.inotify.max_user_watches=2147483647
        else
            wrap_good "- $1" "$(cat "$1")"
        fi
    }

    check_limit_under__max_user_instances() {
        if [ "$(cat "$1")" -lt "$2" ]; then
            wrap_warning "- $1" "$(cat "$1")"
            # echo "Set to $2 to run more nodes"
            echo "sudo sysctl fs.inotify.max_user_instances=2048" 
            # read -n 1 -s -r -p "<Press any key to continue cmd>"
            sudo sysctl fs.inotify.max_user_instances=2048

        else
            wrap_good "- $1" "$(cat "$1")"
        fi
    }

    check_limit_under__max_queued_events() {
        if [ "$(cat "$1")" -lt "$2" ]; then
            wrap_warning "- $1" "$(cat "$1")"
            # echo "Set to $2 to run more nodes"
            echo "sudo sysctl fs.inotify.max_queued_events=2147483647" 
            # read -n 1 -s -r -p "<Press any key to continue cmd>"
            sudo sysctl fs.inotify.max_queued_events=2147483647

        else
            wrap_good "- $1" "$(cat "$1")"
        fi
    }


    # echo 'Limits:'
    check_limit_under__max_user_watches /proc/sys/fs/inotify/max_user_watches 2147483647
    check_limit_under__max_user_instances /proc/sys/fs/inotify/max_user_instances 2048
    check_limit_under__max_queued_events /proc/sys/fs/inotify/max_queued_events 2147483647
    echo


    # SE linux
    check_selinux() {
        if [ -f "/etc/selinux/config" ]; then
            sestatus
            status=$(sestatus  | awk '{print $3}')
            echo $status
            if [ "$status" != "disabled" ] && [ "$status" != "permissive" ] ; then
                wrap_color "  SELinux should be disabled or in permissive mode, for example set: setenforce 0" bold black
                exit 1
            fi
        fi

    }

    echo 'SELinux:'
    check_selinux


}

bin="api"
machine=Linux

o="$(uname -s)"
case "${o}" in
    Linux*) 
            
    machine=Linux;;
    Darwin*)  
    machine=Mac;;
    *)          
    machine="UNKNOWN:${o}"
esac

exit_on_error() {
    exit_code=$1
    last_command=${@:2}
    if [ $exit_code -ne 0 ]; then
        >&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
        exit $exit_code
    fi
}



usage() {
    # echo "$0 -s   - drop to shell"
    echo "qbo start api         -- Start $bin"
    echo " -c                   -- Start clean"
    echo " -d                   -- Start with valgrind"
    echo " -r                   -- Set release type. Default: prod"
    echo " -l { info | debug }  -- Set log level"
    echo "qbo stop api          -- Stop $bin api"
    echo "qbo attach terminal   -- Attach $bin. (CTRL-p, CTL-q) to exit"
    echo "qbo logs api          -- Get $bin logs" 
    echo " -f                   -- Follow logs"
    exit 1
}

function start {

    echo "clean = $clean"
    if [ $clean = 1 ]; then 
        echo "clean start"
        QBO_SHELL=$(docker ps -q --filter "label=io.qbo.shell")
        if [ ! -z "$QBO_SHELL" ]; then
            docker rm $QBO_SHELL -f
        fi
        QBO_CLUSTER=$(docker ps -q --filter "label=io.qbo.cluster")
        if [ ! -z "$QBO_CLUSTER" ]; then
            docker rm $QBO_CLUSTER -f
        fi
        QBO_INSTANCE=$(docker ps -q --filter "label=io.qbo.instance")
        if [ ! -z "$QBO_INSTANCE" ]; then
            docker rm $QBO_INSTANCE -f
        fi
        docker rm qbo -f
        docker system prune -f
        sudo rm -f $QBO_API_DB
        sudo rm -f $QBO_CLI_DB
        sudo rm -f ~/.qbo/api.json
        sudo rm -f ~/.qbo/cli.json
        sudo rm -f ~/.qbo/*.conf
        sudo rm -f ~/.qbo/cmd.log
        sudo rm -f ~/.qbo/qbo.dot
        sudo rm -f ~/.qbo/messages
        touch $HOME/.qbo/messages
        sudo ipvsadm -C
        sudo ipvsadm -Ln
    fi

    if [ ! -d ~/.qbo ]; then
        mkdir ~/.qbo
    fi

    if [ ! -f ~/.qbo/api.json ]; then
       cat << EOF > ~/.qbo/api.json
{
    "docker_runtime":"runc",
    "registry_user":"kindest",
    "registry_auth":"hub.docker.com",
    "registry_token":"",
    "registry_repo":"",
    "registry_hostname":"hub.docker.com",
    "registry_type":"docker"
}
EOF
    fi


    g=0
    if [ $machine = "Linux" ]; then
        echo "OS = $machine"
        run_linux_tests
        if type getent > /dev/null 2>&1; then
            g=$(getent group docker | awk -F ':' '{print $3}')
 
        else
            g=$(cat /etc/group | grep docker: | awk -F ':' '{print $3}')
    
        fi
    else 
        echo "OS = $machine"

        printf "\n"


        wrap_color "# -----WARNING-----" yellow
        wrap_color "# Qbo requires docker.raw.sock to work in MAC OS. " grey
        wrap_color "# While Docker Desktop is running, run the following cmds to fix this: " grey
        wrap_color "sudo rm /var/run/docker.sock" bold white
        wrap_color  "sudo ln -s ~/Library/Containers/com.docker.docker/Data/docker.raw.sock /var/run/docker.sock" bold white
        wrap_color "# Restart Docker Desktop" grey
        wrap_color "# -----WARNING-----" yellow


    fi

    echo "USER = $(whoami)"
    echo "UID = $(id -u)"
    echo "GID = $g"


    opt="";
    if [ $debug = 1 ]; then
        opt="-d";
    fi
    
    if [ $build_type == "stage" ]; then
        i="eadem/$bin"
        docker pull $i
        # Enable if coredumps are needed when valgrind is not running with the '-d' option
        # qbo api coredumps will go under ~/.qbo/
        # --privileged 
        (set -x; docker run --rm --name qbo -d --privileged --net host -it -e QBO_OPTS="--$log_level" -e HUSER=$(whoami) -e HUID=$(id -u) -e HGID=$g -v $HOME/.qbo/:/tmp/qbo/ -v /var/run/docker.sock:/var/run/docker.sock $i "start $opt")
    else
        # prod is in dockerhub
        i="levitas/$bin"
        docker pull $i
        docker run --rm --name qbo -d --privileged --net host -it -e QBO_OPTS="--$log_level" -e HUSER=$(whoami) -e HUID=$(id -u) -e HGID=$g -v $HOME/.qbo/:/tmp/qbo/ -v /var/run/docker.sock:/var/run/docker.sock $i "start $opt"
    fi



    exit_on_error $?
    tail -f ~/.qbo/messages


}

function stop {
    
    qbo_id=`docker ps -aqf "name=qbo$"`

    if [ -z "$qbo_id" ]; then
        echo "qbo $bin not running."
	    exit 1
    fi

    pid=`docker exec $qbo_id ps -ef | grep "[a]pi" | awk -F' ' '{print $2}'`
    if [ ! -z "$pid" ]; then
        docker exec $qbo_id kill -s SIGINT $pid
    fi

    docker stop $qbo_id
    exit_on_error $?
    if [ -f ~/.qbo/valgrind.log ]; then
        tail -f ~/.qbo/valgrind.log
    fi

    exit 0

}

function status {

    docker ps --filter="name=qbo"

}

function logs {

        if [ $follow = 1 ]; then
            tail -f ~/.qbo/messages
        else
            #journalctl -o cat -t $i
            vi ~/.qbo/messages
        fi

        exit 0

}


if [ -z $1 ]; then
    usage
fi

if [ -z $1 ]; then
    usage
fi

if [ $1 = "start" ]; then
    echo -e "\033[38;5;${color}m  => $@\033[0m"
    cmd=$1;
    # move next
    shift $((OPTIND))
    if [ -z $1 ]; then
        usage
    fi
    if [ $1 = "api" ]; then
        bin="api";
    else
        #docker run --rm --name qbo-cli -i -e QBO_OPTS=--debug --user 1000:1000 -v /home/$GITLAB_USER/.qbo:/tmp/qbo qbo-cli-dev valgrind --leak-check=full cli $@
        docker exec qbo cli $@
        exit $?
        #usage
    fi
    shift $((OPTIND))

    while getopts "cdl:r:" opt; do
    case ${opt} in
        r ) # build type

            if [ $OPTARG = "stage" ]; then
                build_type=$OPTARG
            elif [ $OPTARG = "prod" ]; then
                build_type=$OPTARG
                
            else
                usage
            fi
            
        ;;
        c ) 
            echo "-- clean start"
            clean=1;  
        ;;
        d ) 
            echo "-- start debug"
            debug=1;
        ;;
        l ) # ll

            if [ $OPTARG = "info" ]; then
                log_level=$OPTARG
            elif [ $OPTARG = "debug" ]; then
                log_level=$OPTARG
            elif [ $OPTARG = "notice" ]; then
                log_level=$OPTARG
            fi
               
        ;;
        \? ) 
		echo "Invalid option: $OPTARG" 1>&2	
		usage
        ;;
    esac
    done
    start
elif [ $1 = "attach" ]; then
    if [ -z $2 ]; then
        usage
    else 
        if  [[ ! "terminal" =~ "$2".* ]]; then
          usage
        fi
    fi
    docker attach qbo
elif [ $1 = "logs" ]; then
echo -e "\033[38;5;${color}m => $@\033[0m"
    cmd=$1;
    if [ -z $2 ]; then
        usage
    fi
    if [ ! "$2" = "api" ]; then
        usage
    fi
    
    shift $((OPTIND))
    shift $((OPTIND))

    while getopts "f" opt; do
    case ${opt} in
        f )
            follow=1;
			echo "-- follow logs"
        ;;
        \? ) 
		echo "Invalid option: $OPTARG" 1>&2	
		usage
        ;;
    esac
    done
    logs
elif [ $1 = "stop" ]; then
echo -e "\033[38;5;${color}m => $@\033[0m"
    if [ -z $2 ]; then
       usage
    else
        if  [ ! "$2" = "api" ]; then
            usage
        fi
    fi
    
    stop
else
    # local
    # valgrind --leak-check=full
    docker exec qbo cli $@
    exit $?
fi

exit 0
